version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a Java version: 11, 15
        VARIANT: "11"
        # Options
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    environment:
      APP_PORT: 5000
      APP_HOST: 0.0.0.0
      LOG_LEVEL: debug
      MONGO_USERNAME: ${MONGO_USERNAME:?MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST:?MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT:?MONGO_PORT}
      GRAPHIQL_ENABLE: ${GRAPHIQL_ENABLE:?GRAPHIQL_ENABLE}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET}
      JWT_EXPIRE_IN_MINUTES: ${JWT_EXPIRE_IN_MINUTES:?JWT_EXPIRE_IN_MINUTES}
      JWT_ISSUER: ${JWT_ISSUER:?JWT_ISSUER}
    ports:
      - 5000:5000
    command: sleep infinity
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:?MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:?MONGO_PORT}
    depends_on:
      - mongo
