version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    environment:
      APP_PORT: ${APP_PORT?:APP_PORT}
      APP_HOST: ${APP_HOST?:APP_HOST}
    ports:
      - 5000:5000
    command: sleep infinity
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
