version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    environment:
      APP_PORT: 5000
      APP_HOST: 0.0.0.0
      LOG_LEVEL: debug
    ports:
      - 5000:5000
    command: sleep infinity
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
