@baseUri=http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/budget
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJpc3N1ZXIifQ.FgSmi1aRikqCuBD_FwCa6yla30DVc9AgnyF-HAII--U

// @name create
POST {{baseUri}}/api/expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "item": "Snack",
  "price": 3
}

###

// @name update
PUT {{baseUri}}/api/expense/{{create.response.body.$.data.id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "item": "Mineral water",
  "price": 1.50,
  "version": 0
}

###

// @name delete
DELETE {{baseUri}}/api/expense/{{create.response.body.$.data.id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "version": 0
}
